name: s_extensions
description: A dart package aiming to provide useful extensions and helper functions to ease and speed up development.

version: 0.0.2

repository: https://github.com/smith8h/flutter-extensions
homepage: https://github.com/smith8h/flutter-extensions

topics:
  - productivity
  - tools
  - extensions

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
