name: s_extensions
description: A dart package aiming to provide useful extensions and helper functions to ease and speed up development.

version: 1.1.0

repository: https://github.com/smith8h/flutter-extensions
homepage: https://github.com/smith8h/flutter-extensions
screenshots:
  - description: "A definition of the package."
    path: "screenshots/1.png"

topics:
  - productivity
  - utils
  - extensions
  - animations
  - tools

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
