name: s_extensions
description: A powerful and playful extensions dependency for your flutter projects.

version: 0.0.0

repository: https://github.com/smith8h/flutter-extensions
homepage: https://github.com/smith8h/flutter-extensions

topics:
  - productivity
  - tools
  - extensions

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
